# Porta do servidor em ambiente dev (opcional)
server.port=8080

# Configurações do banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/brecho
spring.datasource.username=christian
spring.datasource.password=mysql
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialeto e configurações JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuração do JWT
api.security.secret=minhaChaveSecretaDev123
api.security.expiration=86400000
